# Generated by Django 4.2.4 on 2024-02-05 06:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 5, 6, 58, 17, 202784, tzinfo=datetime.timezone.utc)),
        ),
    ]
